### ISSUE TITLE
Double digit physical drives cannot be specified in config file with exact name

### ISSUE THREAD

**Issue by side1out** [oberstet/iometer#1]
in Worker.cpp...

The code below is applied to physical drives as well as logical drives.  It does not work correctly for double digit physical drives.  It assumes that the colon will be the second character.  This makes it more difficult to dynamically create a config file as the device description has to match exactly only for physical drives > 9.     

		if (IsType(Type(), GenericDiskType)) {
			CString fileDiskName(tgt_name);	//isolate "drive:" portion of name (bug #369)

			**if (fileDiskName[1] == ':')
				fileDiskName = fileDiskName.Left(2);**

			//Find matching disk spec (drive portion only, if formatted).
			int interface_count = manager->InterfaceCount(tgt_type);
			Target_Spec *tspec;
			int counter;

			for (counter = 0; counter < interface_count; counter++) {
				// Yes, GetInterface is used to get Disk tspecs, too.
				tspec = manager->GetInterface(counter, tgt_type);

				CString thisDiskName(tspec->name);

				**if (thisDiskName[1] == ':')
					thisDiskName = thisDiskName.Left(2);**

				if (fileDiskName.CompareNoCase(thisDiskName) == 0)
					break;
			}

**Comment by oberstet** [comment]
the repo here is just a 3 year old copy of upstream http://www.iometer.org/ with no modification at all - pls report any issue to upstream
